name: Build Dockerfiles with detected changes

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main 

jobs:
  Test xenial build:
    name: build xenial
    uses: ./.github/workflows/xenial.yml
  
  Test stretch build:  
    name: stretch build
    uses: ./.github/workflows/stretch.yml

  Test jessie build:
    name: jessie build
    uses: ./.github/workflows/jessie.yml