name: Build Dockerfiles with detected changes

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main 
    paths:
      - debian/*/Dockerfile
      - ubuntu/*/Dockerfile

jobs:
  test-xenial-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: build xenial
        uses: ./.github/workflows/xenial.yml
  
  test-stretch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: stretch build
        uses: ./.github/workflows/stretch.yml

  test-jessie-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: jessie build
        uses: ./.github/workflows/jessie.yml