name: Build Dockerfiles with detected changes

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main 

jobs:
  test xenial build:
    on:
      paths: 
        - ubuntu/xenial/Dockerfile
    uses: .github/workflows/xenial.yml@main
  
  test stretch build:
    on:
      paths: 
        - debian/stretch/Dockerfile
    uses: stretch.yml@main

  test jessie build:
    on:
      paths: 
        - debian/jessie/Dockerfile
    uses: jessie.yml@main


