name: Build Dockerfiles with detected changes

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'ubuntu/*/Dockerfile'
      - 'debian/*/Dockerfile'
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debug
        uses: hmarr/debug-action@v2
