name: Build Dockerfiles with detected changes

on:
  pull_request:
    types: [push,ready_for_review]
    branches:
      - main 
    paths:
      - debian/*/Dockerfile
      - ubuntu/*/Dockerfile

jobs:
  test-xenial-build:
    uses: ./.github/workflows/xenial.yml
  
  test-stretch-build:
    uses: ./.github/workflows/stretch.yml

  test-jessie-build:
    uses: ./.github/workflows/jessie.yml