name: Build Dockerfiles with detected changes

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main 

jobs:
    name: test xenial build
    uses: ./.github/workflows/xenial.yml
  
    name: test stretch build
    uses: ./.github/workflows/stretch.yml

    name: test jessie build
    uses: ./.github/workflows/jessie.yml